FROM openjdk:8-jdk-alpine
COPY ./build/libs/aircompany-rest-java-1.0-SNAPSHOT-all.jar /app/aircompany-rest-java-1.0-SNAPSHOT-all.jar
ENTRYPOINT ["java","-jar","/app/aircompany-rest-java-1.0-SNAPSHOT-all.jar"]